name = "basic-depac"
version = "0.5.0"
author = "Marte Voorneveld"
maintainer = "marte.voorneveld@rivm.nl"
copyright = "Copyright 2025, RIVM"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
DepAC.git = "https://github.com/rivm-syso/DepAC.git"
# Use a specific tag or commit for reproducibility, e.g.:
# DepAC.tag = "5.0.0"
